#!/bin/bash

CON=$((RANDOM%8))
OPMASK=0
while [ $OPMASK -eq 0 ]
do
	OPMASK=$((RANDOM%16))
done
TL=$((RANDOM%10))
FL=$((RANDOM%8))

echo -n CON=$CON OPMASK=$OPMASK FL=$FL TL=$TL " "
if go $CON $OPMASK $TL $FL > test_fl.temp
then
	echo TEST PASS
	exit 0
else
	echo TEST FAIL
	exit 1
fi


