#!/bin/bash

for i in *asm; do
	filename=$(basename $i .asm)
	echo $filename
	# rm -f out/${filename}.*
	as9 "$i" -bin l | tee ${filename}.log
	if grep -q ERROR ${filename}.log; then
		echo ERROR
		exit 1
	fi
	hexdump  -v -e '/1 "%02X\n"' ${filename}.bin > ${filename}.hex
done

mv *{bin,hex,log,lst} out
