../../hdl/jt51_phinc_rom.v
../../hdl/jt51_sintable.v
../../hdl/jt51_exptable.v
../../hdl/jt51_lin2exp.v
../../hdl/jt51_exp2lin.v
../../hdl/jt51_mmr.v
../../hdl/jt51_reg.v
../../hdl/jt51.v
../../hdl/jt51_acc.v
../../hdl/jt51_timers.v
../../hdl/jt51_envelope.v
../../hdl/jt51_op.v
../../hdl/jt51_sh.v
../../hdl/jt51_sh2.v
../../hdl/jt51_sum_op.v
../../hdl/jt51_phasegen.v
../../hdl/jt51_lfo.v
../../hdl/jt51_lfo_lfsr.v
../../hdl/jt51_pm.v
../../hdl/jt51_noise.v
../../hdl/jt51_noise_lfsr.v
../../hdl/jt51_kon.v
