../../hdl/jt51_phinc_rom.v
../../hdl/jt51_exprom.v
../../hdl/jt51_phrom.v
../../hdl/jt51_lin2exp.v
../../hdl/jt51_exp2lin.v
../../hdl/jt51_mmr.v
../../hdl/jt51_reg.v
../../hdl/jt51.v
../../hdl/jt51_acc.v
../../hdl/jt51_timers.v
../../hdl/jt51_eg.v
../../hdl/jt51_op.v
../../hdl/jt51_sh.v
../../hdl/jt51_pg.v
../../hdl/jt51_lfo.v
../../hdl/jt51_lfo_lfsr.v
../../hdl/jt51_pm.v
../../hdl/jt51_noise.v
../../hdl/jt51_noise_lfsr.v
../../hdl/jt51_kon.v
../../hdl/jt51_mod.v
