#!/bin/bash

# This simulation compares the phase modulation RTL implementation
# with the C++ model

verilator --cc ../../hdl/jt51_{pg,pm,sh,phinc_rom}.v test.cc tables.cc opm.c \
    --exe --top-module jt51_pg -DJT51_PG_SIM

export CPPFLAGS=-O2

if ! make -j -C obj_dir -f Vjt51_pg.mk Vjt51_pg > mk.log; then
    cat mk.log
    exit $?
fi

rm mk.log
obj_dir/Vjt51_pg