#!/bin/bash
UART=/dev/ttyUSB0
stty -F $UART 921600 raw -echo
echo Volcando...
cat 21j-0-1 > $UART

# echo Volcado completo

# i=1
# while [ $i -lt 31 ]; do
# 	x=$(printf "%X" $i)
# 	echo Cancion 0x$x
# 	echo -e -n "\x$x" > $UART
# 	timeout 8m cat $UART > $x.jtx
# 	echo -e -n "\x$FF" > $UART
# 	i=$((i+1))
# done

echo -e -n "\x1" > $UART

reset
